References

 * [Basic indexing](https://numpy.org/doc/stable/reference/arrays.indexing.html#indexing)

 * [Definition of ‘view’](https://numpy.org/doc/stable/glossary.html#term-view)
 
 * [Advanced Indexing](https://numpy.org/doc/stable/reference/arrays.indexing.html#advanced-indexing)



In [2]:
import numpy as np

1. __Ellipsis__:  
Given a N-dimensional array, x, index into x such that you access entry-0 of axis-0, the last entry of axis-N−1, slicing along all intermediate dimensions. N is at least 2.

In [14]:
x = np.random.rand(2, 2, 3)

print(x)
print("\n")



print( x[0, ..., -1] )
print("\n")
print( x[0, Ellipsis, -1] )


[[[0.43371126 0.17510431 0.60663104]
  [0.46880833 0.23852707 0.34575032]]

 [[0.43361084 0.92375237 0.28685423]
  [0.33044591 0.80702232 0.56910995]]]


[0.60663104 0.34575032]


[0.60663104 0.34575032]


2. Given a shape-(4, 3) array,
```
arr = np.array([[ 0,  1,  2,  3],
                [ 4,  5,  6,  7],
                [ 8,  9, 10, 11]])
```
                
which of the following indexing schemes perform basic indexing? That is, in which instances does the index satisfy the rules of basic indexing?

`arr[0]`

`arr[:-1, 0]`

`arr[(2, 3)]`

`arr[[2, 0]]`

`arr[np.array([2, 0])]`

`arr[(0, 1), (2, 3)]`

`arr[slice(None), ...]`

`arr[(np.newaxis, 0, slice(1, 2), np.newaxis)]`

3. Given,
```
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
```

Which of the following expressions create views of `a`? That is, in which cases do `a` and the created variable reference the same underlying array data? Check your work by using `np.shares_memory`.

`a1 = a`

`a2 = a[0, 0]`

`a3 = a[:, 0]`

`a4 = a[:, 0] + np.array([-1, -2, -3])`

`a5 = np.copy(a[:, 0])`

`a6 = a[np.newaxis]`

`a7 = a.reshape(2, 3, 2)`

`a8 = 2 + a`

4. Augmenting Array Data In-Place

Given,
```
x = np.array([[ 0.,  1.,  2.,  3.],
              [ 4.,  5.,  6.,  7.],
              [ 8.,  9., 10., 11.]])

y = x[0, :]
```
Which of the following expressions updates the data originally referenced by `x`?

a. `x += 3`

b. `y *= 2.4`

c. `x = x + 3`

d. `y = np.copy(y) 
   y += 3`

e. `np.log(x[1:3], out=x[1:3])`

f. `y[:] = y + 2`

g. `x = np.square(x)`

h. `x[:] = 0`

i. `def f(z): z /= 3 
   f(y)`

j. `np.square(y, out=y)`

## Advanced Indexing


5. Given the following array:

`y = np.array([ 0, -1, -2, -3, -4, -5])`

Use advanced indexing, using an integer-array, to produce the following arrays:

a. 
`array([-1])`

b. 
`array([-1, -2, -1, -2])`

c. 
`array([[ 0, -5], 
       [-1, -4]])`

d. 
`array([[-2], 
       [-3], 
       [-2]])`

6. Given the following array:
```
z = np.array([[[ 0,  1,  2,  3],
               [ 4,  5,  6,  7],
               [ 8,  9, 10, 11]],

              [[12, 13, 14, 15],
               [16, 17, 18, 19],
               [20, 21, 22, 23]]])
```
Use advanced indexing, using integer-arrays, to produce the following arrays:

a. 
`array([[ 0,  5, 10],
       [12, 17, 22]])`

b. 
`array([[ 0, 23],
       [23,  0]])`