In [56]:
import numpy as np

0. A digital image is simply an array of numbers, which instructs a grid of pixels on a monitor to shine light of specific colors, according to the numerical values in that array.

An RGB-image can thus be stored as a 3D NumPy array of shape-(V,H,3). V is the number of pixels along the vertical direction, H is the number of pixels along the horizontal, and the size-3 dimension stores the red, blue, and green color values for a given pixel. Thus a (32, 32, 3) array would be a 32x32 RBG image.

It is common to work with a collection of images. Suppose we want to store N images in a single array; thus we now consider a 4D shape-(N, V, H, 3) array.

Let's collect some statistics on a collection of images. For the sake of convenience, let's simply generate a 4D-array of random numbers as a placeholder for real image data. We will generate 100, 32x32 RGB images:

`images = np.random.rand(100, 32, 32, 3)`

Now, compute the following (5 different problems): 

In [3]:
images = np.random.rand(100, 32, 32, 3)

In [7]:
#a. The average 32x32 RGB image.
np.mean(images,axis=0)

array([[[0.53554714, 0.53976622, 0.531514  ],
        [0.48773237, 0.50873074, 0.48085293],
        [0.51469939, 0.52222588, 0.47809808],
        ...,
        [0.51908462, 0.45555684, 0.47437542],
        [0.48880838, 0.49760301, 0.53982126],
        [0.48614742, 0.48626743, 0.54637513]],

       [[0.50135863, 0.51564852, 0.52117644],
        [0.49809201, 0.49709799, 0.54600344],
        [0.44983872, 0.48127384, 0.50709029],
        ...,
        [0.49830918, 0.46593004, 0.44421581],
        [0.48446615, 0.51457748, 0.50610812],
        [0.49730165, 0.49674961, 0.45257231]],

       [[0.49273241, 0.4975042 , 0.55163125],
        [0.47299029, 0.51061877, 0.51725307],
        [0.48391579, 0.49375616, 0.51134419],
        ...,
        [0.49460112, 0.51676856, 0.50905822],
        [0.4697599 , 0.52051981, 0.52260194],
        [0.51462695, 0.53271545, 0.55694555]],

       ...,

       [[0.49712901, 0.53489573, 0.44031173],
        [0.48627386, 0.48501566, 0.54995706],
        [0.46193957, 0

In [8]:
#b. The total sum of all the values in the array.
np.sum(images)

153761.37211837247

In [12]:
#c. The minimum blue value, respective to each image.
np.array(np.min(images[:,:,:,2],axis=(1,2)))

array([1.98560554e-03, 3.71381013e-04, 9.29746555e-06, 8.02821242e-04,
       3.46155421e-05, 4.63354701e-04, 1.88678368e-03, 8.32219434e-04,
       2.90305773e-03, 2.07944272e-03, 5.50878916e-04, 1.28117502e-03,
       8.45691361e-04, 1.62730022e-03, 1.69359665e-04, 7.14992501e-05,
       4.22350022e-04, 9.35971689e-04, 9.59683934e-05, 1.41158558e-03,
       1.20596184e-03, 6.83270716e-04, 6.17988744e-04, 1.52598666e-03,
       3.16204660e-04, 1.74467032e-03, 5.32276848e-04, 2.58611682e-05,
       4.35026957e-03, 7.03012629e-04, 1.07844845e-05, 1.04950612e-04,
       1.49019788e-04, 6.31960467e-04, 1.02590272e-03, 4.40187806e-04,
       1.42945179e-04, 3.28050129e-04, 1.09782891e-04, 9.69254864e-04,
       4.58861185e-04, 2.08219761e-03, 1.36972114e-04, 7.50535738e-05,
       3.50553335e-04, 2.91105674e-04, 1.83864487e-03, 3.06339137e-04,
       2.49637473e-03, 1.83097752e-04, 9.30674400e-04, 1.34410628e-03,
       9.11451239e-04, 3.82808531e-03, 1.38258279e-03, 4.29661088e-04,
      

In [15]:
#d. The standard deviation among all the RGB values in all the images, 
#   respective to each pixel position (thus you should produce a shape-(32, 32) array of values).
np.array(np.std(images, axis=(0,3)))

array([[0.29229319, 0.29045089, 0.28519049, ..., 0.29920384, 0.29088339,
        0.29538297],
       [0.29632948, 0.28711337, 0.28975904, ..., 0.29273412, 0.28739439,
        0.29007975],
       [0.28708705, 0.29023734, 0.28287243, ..., 0.28450384, 0.29455449,
        0.27951342],
       ...,
       [0.28893048, 0.29046789, 0.28777867, ..., 0.29601913, 0.27561881,
        0.30033173],
       [0.27048899, 0.28971991, 0.29640963, ..., 0.30102248, 0.29294905,
        0.28959218],
       [0.28787842, 0.28939348, 0.28041737, ..., 0.27677976, 0.29693148,
        0.2875361 ]])

In [16]:
#e. The maximum red-value in the top-left quadrant, respective to each image.
np.amax(images[:,:16,:16,0], axis=(1,2))

array([0.98867746, 0.99801221, 0.99939201, 0.99648311, 0.99858762,
       0.9988705 , 0.99299707, 0.99615862, 0.99820672, 0.99317874,
       0.99754645, 0.99844953, 0.99344767, 0.9959485 , 0.98792345,
       0.9959063 , 0.99978102, 0.99877863, 0.99965398, 0.99630737,
       0.9950148 , 0.99865799, 0.99724858, 0.99305477, 0.98205338,
       0.9971089 , 0.99587002, 0.9990337 , 0.99423948, 0.99710869,
       0.99425029, 0.99937449, 0.99954479, 0.99978819, 0.99814853,
       0.99970437, 0.99276193, 0.99701484, 0.99543544, 0.99920214,
       0.99789232, 0.99931647, 0.99849774, 0.99100729, 0.99971973,
       0.99959209, 0.99241397, 0.99988559, 0.98752997, 0.99793768,
       0.99795394, 0.99825313, 0.99999132, 0.99048981, 0.99775443,
       0.99576752, 0.99535296, 0.99562556, 0.99606053, 0.99889479,
       0.99847858, 0.99677097, 0.99906886, 0.99895741, 0.99668913,
       0.99557908, 0.99970367, 0.99990713, 0.99739009, 0.99852252,
       0.99899323, 0.99934604, 0.9987268 , 0.9982101 , 0.99941

1. Given the following pairs of array-shapes, determine what the resulting broadcasted shapes will be. Indicate if a pair is broadcast-incompatible.

 * 7 x 2 with 7

 * 4 with 3 x 4

 * 1 x 3 x 1 with 8 x 1 x 1

 * 9 x 2 x 5 with 2 x 5

 * 3 with 3 x 3 x 2

In [28]:
x=np.random.rand(4)
y=np.random.rand(3,4)
(x*y).shape

#Incompatable
#3 x 4
#8 x 3 x 1
#9 x 2 x 5
#Incompatable

(3, 4)

2. Generate a random array of 10,000 2D points using `np.random.rand`. Compute the “center of mass” of these points, which is simply the average x-coordinate and the average y-coordinate of these 10,000 points. Then, use broadcasting to compute the shape-(10000, 2) array that stores the position of the points relative to the center of mass. For example, if the center of mass is `(0.5,1)`, and the absolute position of a point is `(2,3)`, then the position of that point relative to the center of mass is simply `(2,3)−(0.5,1)=(1.5,2)`



In [34]:
arr = np.random.rand(10000,2)
com = arr.mean(axis=0)
print(com)
print(arr-com)

[0.49658287 0.50419522]
[[-1.27419560e-01 -3.76794649e-04]
 [ 2.77718698e-01 -7.05051136e-02]
 [-2.10773028e-01  4.95193920e-01]
 ...
 [-4.54067823e-01  4.91532124e-01]
 [ 3.98198477e-01 -2.19302342e-01]
 [-3.16298953e-01  9.66030172e-02]]


3. Given the shape-(2,3,4) array:
```
x = np.array([[[ 0,  1,  2,  3],
               [ 4,  5,  6,  7],
               [ 8,  9, 10, 11]],

              [[12, 13, 14, 15],
               [16, 17, 18, 19],
               [20, 21, 22, 23]]])
```
Normalize `x` such that _each of its rows, within each sheet, will sum to a value of 1_. Make use of the sequential function `np.sum`, which should be called only once, and broadcast-division.

In [42]:
x = np.array([[[ 0,  1,  2,  3],
            [ 4,  5,  6,  7],
            [ 8,  9, 10, 11]],

           [[12, 13, 14, 15],
            [16, 17, 18, 19],
            [20, 21, 22, 23]]])
y = np.ndarray.sum(x,axis=2).reshape(2,3,1)
x = x/y
z = np.ndarray.sum(x,axis=2)
x
#z

array([[[0.        , 0.16666667, 0.33333333, 0.5       ],
        [0.18181818, 0.22727273, 0.27272727, 0.31818182],
        [0.21052632, 0.23684211, 0.26315789, 0.28947368]],

       [[0.22222222, 0.24074074, 0.25925926, 0.27777778],
        [0.22857143, 0.24285714, 0.25714286, 0.27142857],
        [0.23255814, 0.24418605, 0.25581395, 0.26744186]]])

4. A digital image is simply an array of numbers, which instructs a grid of pixels on a monitor to shine light of specific colors, according to the numerical values in that array.

An RGB-image can thus be stored as a 3D NumPy array of shape-(V,H,3). V is the number of pixels along the vertical direction, H is the number of pixels along the horizontal, and the size-3 dimension stores the red, blue, and green color values for a given pixel. Thus a (32,32,3) array would be a 32x32 RGB image.

You often work with a collection of images. Suppose we want to store N images in a single array; thus we now consider a 4D shape-(N, V, H, 3) array. For the sake of convenience, let’s simply generate a 4D-array of random numbers as a placeholder for real image data. We will generate 500, 48x48 RGB images:

`images = np.random.rand(500, 48, 48, 3)`

Using the sequential function `np.max` and broadcasting, normalize `images` such that the largest value within _each color-channel of each image is 1_.

In [55]:
images = np.random.rand(500, 48, 48, 3)
maxvals = np.max(images,axis=(1,2))
images = images/maxvals.reshape(500,1,1,3)
np.max(images,axis=(1,2))
np.all(images.max(axis=(1,2)) == 1)

True

5.  Use the function numpy.allclose to verify that the three methods for computing the pairwise distances produce the same numerical results. 

The three functions we covered in class were: 

 * `pairwise_dists_looped(x, y)`

 * `pairwise_dists_crude(x, y)`

 * `pairwise_dists(x, y)`

If you didn't get them completed, you can find each of them here. 
[https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/Broadcasting.html](https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/Broadcasting.html)