## NumPy

You may reference the following documentation if you need to look up something: 

 * [NumPy Basics](https://numpy.org/doc/stable/user/basics.html#numpy-basics)
 * [NumPy reference](https://numpy.org/doc/stable/reference/index.html)
 * [The N-dimensional array](https://numpy.org/doc/stable/reference/arrays.ndarray.html)
 * [Array indexing](https://numpy.org/doc/stable/user/basics.indexing.html#indexing)
 * [Indexing routines](https://numpy.org/doc/stable/reference/routines.indexing.html#indexing-routines)
 * [Array manipulation routines](https://numpy.org/doc/stable/reference/routines.array-manipulation.html)
 * [Array attributes](https://numpy.org/doc/stable/reference/arrays.ndarray.html#array-attributes)
 * [Routines for iterating over arrays](https://numpy.org/doc/stable/reference/routines.indexing.html#iterating-over-arrays)
 * [Detailed description of array iteration](https://numpy.org/doc/stable/reference/arrays.nditer.html#iterating-over-arrays)

In [ ]:
import numpy as np


1. Convert a 1-D array with 12 elements into a 2-D array

2. Convert 1-D array with 8 elements to 3-D array with 2x2 elements.

3. Given the 3D, shape-(3, 3, 3) array (see below): 

In [ ]:
#Problem 3

"""
Given the 3D, shape-(3, 3, 3) array:

arr = np.array([[[ 0,  1,  2],
                 [ 3,  4,  5],
                 [ 6,  7,  8]],

                [[ 9, 10, 11],
                 [12, 13, 14],
                 [15, 16, 17]],

                [[18, 19, 20],
                 [21, 22, 23],
                 [24, 25, 26]]])
Index into the array to produce the following results

#1
array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

#2
array([[ 3,  4,  5],
       [12, 13, 14]])

#3
array([2, 5])

#4
array([[11, 10,  9],
       [14, 13, 12],
       [17, 16, 15]])
"""

4. Given the 2D array:

`x = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11],
              [12, 13, 14, 15]])`

Take the natural-logarithm of the 1st and 3rd element in the 3rd-row of x, producing a shape-(2,) result.

5. Given the 2D array:

`x = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11],
              [12, 13, 14, 15]])`
              
Add the four quadrants of x, producing a shape-(2, 2) output.