This quiz is "open Jupyter Notebook," meaning you can look in other Jupyter Notebooks that you have created. You can also reference notes you have taken by hand, if applicable. Additionally, you can reference the official Python documentation: https://docs.python.org/3/library/ or NumPy documentaion https://numpy.org/doc/stable/index.html. You _cannot_ search for answers on forums, blogs, etc. 

You should _not_ use for loops for any solution in this quiz. 

10 problems, 10 points each, total of 100 points. 

In [117]:
import numpy as np

1. (10 points) Use NumPy functions to create the following array, using one line of code: 
```
arr1 = array([[[ 0,  1,  2,  3],
               [ 4,  5,  6,  7],
               [ 8,  9, 10, 11],
               [12, 13, 14, 15]],

              [[16, 17, 18, 19],
               [20, 21, 22, 23],
               [24, 25, 26, 27],
               [28, 29, 30, 31]],

              [[32, 33, 34, 35],
               [36, 37, 38, 39],
               [40, 41, 42, 43],
               [44, 45, 46, 47]],

              [[48, 49, 50, 51],
               [52, 53, 54, 55],
               [56, 57, 58, 59],
               [60, 61, 62, 63]]])
```





In [118]:
arr1 = np.array(range(64)).reshape(4,4,4)
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

2. (10 points) Using array `arr1` from problem 1, index/slice into it (using one line of code) to produce the following: 

2a. (3 points)

```array([[33, 34],
          [37, 38],
          [41, 42],
          [45, 46]]) ```

In [119]:
arr1[[[2,2],[2,2],[2,2],[2,2]],[[0,0],[1,1],[2,2],[3,3]],[[1,2],[1,2],[1,2],[1,2]]]

array([[33, 34],
       [37, 38],
       [41, 42],
       [45, 46]])

2b. (3 points)
<code>
array([[[26, 27],
        [30, 31]], 
</code>
<code>
       [[42, 43],
        [46, 47]]])
</code>

In [120]:
arr1[[[[1,1],[1,1]],[[2,2],[2,2]]],[[[2,2],[3,3]],[[2,2],[3,3]]],[[[2,3],[2,3]],[[2,3],[2,3]]]]

array([[[26, 27],
        [30, 31]],

       [[42, 43],
        [46, 47]]])

2c. (4 points)
<code>
array([[[ 7,  6,  5,  4],
        [ 3,  2,  1,  0]],
</code>
<code>
       [[23, 22, 21, 20],
        [19, 18, 17, 16]],
</code>
<code>
       [[39, 38, 37, 36],
        [35, 34, 33, 32]]])
</code>

In [121]:
arr1[[[[0,0,0,0],[0,0,0,0]],[[1,1,1,1],[1,1,1,1]],[[2,2,2,2],[2,2,2,2]]],[[[1,1,1,1],[0,0,0,0]],[[1,1,1,1],[0,0,0,0]],[[1,1,1,1],[0,0,0,0]]],[[[3,2,1,0],[3,2,1,0]],[[3,2,1,0],[3,2,1,0]],[[3,2,1,0],[3,2,1,0]]]]

array([[[ 7,  6,  5,  4],
        [ 3,  2,  1,  0]],

       [[23, 22, 21, 20],
        [19, 18, 17, 16]],

       [[39, 38, 37, 36],
        [35, 34, 33, 32]]])

3. (10 points) Create a shape-(24,) array named `arr2`. 

In [122]:
arr2 = np.ones(24)
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1.])

How many ways can it be reshaped into a 3-dimensional array (without using `1` as one of the dimensions)?  List each way. 

In [123]:
#arr2.reshape(2,2,6)
#arr2.reshape(6,2,2)
#arr2.reshape(2,6,2)
#arr2.reshape(4,2,3)
#arr2.reshape(2,4,3)
#arr2.reshape(3,4,2)
#arr2.reshape(3,2,4)
#arr2.reshape(4,3,2)
#arr2.reshape(2,3,4)

4.  (10 points) We went over this way to create an array in class: `np.array([[[0]*4]*3]*2)`

4a. (3 points) Use this approach to create a shape-(3,2,5) array filled with 1s. 

In [124]:
np.array([[[1]*5]*2]*3)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

4b. (2 points) Use the ones function to create the same shaped array.

In [125]:
np.ones([3,2,5])

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

4c. (3 points) What is the difference between the two arrays? (Explain)

In [126]:
#The first array has the ones as integers, while the np.ones() function has the ones as floats

4d. (2 points) Show one way you could make them each have the same data type. 

In [127]:
np.array([[[1.]*5]*2]*3)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

5a. (1 point) Create an array named `arr3` with shape-(5,4), filled with random numbers based on a uniform distribution (values range from 0 to 1). 

In [130]:
arr3 = np.random.rand(5,4)
arr3

array([[0.1809528 , 0.37146683, 0.18369398, 0.4821259 ],
       [0.3135267 , 0.23244165, 0.28420166, 0.9423012 ],
       [0.82006593, 0.31076798, 0.47828336, 0.83119965],
       [0.71512378, 0.31525426, 0.21251117, 0.56401966],
       [0.03103537, 0.80300659, 0.94306629, 0.88929848]])

5b. (1 point) Square each element in the top row of the array. 

In [131]:
arr3[0] = arr3[0]**2
arr3

array([[0.03274391, 0.1379876 , 0.03374348, 0.23244539],
       [0.3135267 , 0.23244165, 0.28420166, 0.9423012 ],
       [0.82006593, 0.31076798, 0.47828336, 0.83119965],
       [0.71512378, 0.31525426, 0.21251117, 0.56401966],
       [0.03103537, 0.80300659, 0.94306629, 0.88929848]])

5c. (2 points) Take the square root of each element in the final column in the array. 

In [132]:
arr3[:,-1] = arr3[:,-1]**0.5
arr3

array([[0.03274391, 0.1379876 , 0.03374348, 0.4821259 ],
       [0.3135267 , 0.23244165, 0.28420166, 0.970722  ],
       [0.82006593, 0.31076798, 0.47828336, 0.91170151],
       [0.71512378, 0.31525426, 0.21251117, 0.75101242],
       [0.03103537, 0.80300659, 0.94306629, 0.94302623]])

5d. (2 points) Add 1 to each element in the the middle row

In [133]:
arr3[2] += 1
arr3

array([[0.03274391, 0.1379876 , 0.03374348, 0.4821259 ],
       [0.3135267 , 0.23244165, 0.28420166, 0.970722  ],
       [1.82006593, 1.31076798, 1.47828336, 1.91170151],
       [0.71512378, 0.31525426, 0.21251117, 0.75101242],
       [0.03103537, 0.80300659, 0.94306629, 0.94302623]])

5e. (2 points) Sum all of the entries of the array to produce one value. Use a NumPy function, not for loops! 

In [134]:
np.sum(arr3)

13.722347815930702

5f. (2 points) Sum over all of the rows to produce one value per column. Use a NumPy function, not for loops! 

In [135]:
np.sum(arr3, axis=0)

array([2.9124957 , 2.7994581 , 2.95180595, 5.05858807])

6. (10 points) Use the following two arrays: 


In [136]:
x = np.array([[ 11,   6,   3],
                 [ -9,   2,  17],
                 [  8,   0,   1]])

y = np.array([[  1,   0,  7],
                 [ -4,  -1,  4],
                 [-10,  15, 19]])

6a. (5 points) Add column-1 of `x` and row-0 of `y`

In [137]:
x[:,1] + y[0]

array([7, 2, 7])

6b. (5 points) Take the mean average of row 2 of `x` and multiply it by the maximum value in column 0 of `y`

In [138]:
np.mean(x[2])*np.max(y[:,0])

3.0

7. (10 points) Given the array `arr4` depicting scores that 8 manufactured parts received on 5 criteria (for example: straightness, flatness, concentricity, perpendicularity, parallelism): 



In [139]:
arr4 = np.array([[0.95, 0.84, 0.71, 0.60, 0.63],
       [0.93, 0.77, 0.87, 0.75, 0.83],
       [0.74, 0.79, 0.99, 0.70, 0.85],
       [0.67, 0.66, 0.63, 0.98, 0.64],
       [0.92, 0.92, 0.79, 0.89, 0.82],
       [0.63, 0.81, 0.95, 0.78, 0.88],
       [0.90, 0.74, 0.85, 0.88, 0.9 ],
       [0.94, 0.78, 0.86, 0.97, 0.91]]) 

7a. (3 points) Compute the mean score for each part (rounded to 2 decimal places). No for loops!


In [140]:
np.mean(arr4,axis=0).round(2)

array([0.84, 0.79, 0.83, 0.82, 0.81])

7b. (4 points) A part must achieve a mean score of 0.80 to pass. However, if any individual criteria score is less than 0.70, then that criteria fails and the score for that criteria must be set to zero; and then the mean is calculated again. Set all individual criteria scores that are less than 0.70 to 0.00 (without using for loops). 

In [141]:
boolarr = arr4 < 0.8
arr4[boolarr] = 0.0
arr4

array([[0.95, 0.84, 0.  , 0.  , 0.  ],
       [0.93, 0.  , 0.87, 0.  , 0.83],
       [0.  , 0.  , 0.99, 0.  , 0.85],
       [0.  , 0.  , 0.  , 0.98, 0.  ],
       [0.92, 0.92, 0.  , 0.89, 0.82],
       [0.  , 0.81, 0.95, 0.  , 0.88],
       [0.9 , 0.  , 0.85, 0.88, 0.9 ],
       [0.94, 0.  , 0.86, 0.97, 0.91]])

7c. (3 points) Compute the means for each part again. How many parts now pass (having a score >= 0.80)?

In [142]:
#No criteria pass
np.mean(arr4,axis=0)

array([0.58   , 0.32125, 0.565  , 0.465  , 0.64875])

8. (10 points) Given the two arrays `a` and `b` below, use the `reshape` function to allow them to be multiplied together and to produce a shape-(4, 5) array. 

In [143]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 5, 6, 7, 8])



In [144]:
a.reshape(1,4)*b.reshape(5,1)

array([[ 4,  8, 12, 16],
       [ 5, 10, 15, 20],
       [ 6, 12, 18, 24],
       [ 7, 14, 21, 28],
       [ 8, 16, 24, 32]])

9. (10 points) In class, we looked at the following example of combining basic and advanced indexing using a Boolean Index-Array: 

<code>
x = np.array([[[ 0,  1,  2,  3],
               [ 4,  5,  6,  7],
               [ 8,  9, 10, 11]],

              [[12, 13, 14, 15],
               [16, 17, 18, 19],
               [20, 21, 22, 23]]])

ind0 = np.array([True, False])
</code>

Select sheet-0, all rows, last column: 
<code>
x[ind0, :, -1]
</code>

Which produced: 
`array([[ 3,  7, 11]])`

Using the following array `z`, come up with a Boolean Index Array and apply it to `z` to return only the diagonal values. 


In [145]:
z = np.array([[[ 0,  1,  2,  3],
               [ 4,  5,  6,  7],
               [ 8,  9, 10, 11],
               [ 12, 13, 14, 15]
               ],

              [
               [16, 17, 18, 19],
               [20, 21, 22, 23], 
               [24, 25, 26, 27],
               [28, 29, 30, 31]]])


In [146]:
boolarr = np.eye(4,4) > 0
z[:,boolarr]

array([[ 0,  5, 10, 15],
       [16, 21, 26, 31]])

10. (10 points)

10a. (3 points) Given the array `z` from problem 9 above, create an index array called `rows` and another called `cols` and combine basic and advanced indexing by applying `rows` and `cols` to `z` to produce the corner elements of the array `z`.  

In [147]:
rows = [[0,0],[-1,-1]]
cols = [[0,-1],[-1,0]]
z[:,rows,cols]

array([[[ 0,  3],
        [15, 12]],

       [[16, 19],
        [31, 28]]])

10b. (2 points) Set the corner elements in `z` to the value of `99`. 

In [148]:
z[:,rows,cols] = 99
z

array([[[99,  1,  2, 99],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [99, 13, 14, 99]],

       [[99, 17, 18, 99],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [99, 29, 30, 99]]])

10c. (3 points) Use a one-line logic statement to create a boolean index array called `mask` where `True` represents the position of even-numbered elements. 

In [149]:
mask = z%2 == 0
mask

array([[[False, False,  True, False],
        [ True, False,  True, False],
        [ True, False,  True, False],
        [False, False,  True, False]],

       [[False, False,  True, False],
        [ True, False,  True, False],
        [ True, False,  True, False],
        [False, False,  True, False]]])

10d. (2 points) Use the `mask` array created in 10c to set all `True` positions to `0`. 

In [150]:
z[mask] = 0
z

array([[[99,  1,  0, 99],
        [ 0,  5,  0,  7],
        [ 0,  9,  0, 11],
        [99, 13,  0, 99]],

       [[99, 17,  0, 99],
        [ 0, 21,  0, 23],
        [ 0, 25,  0, 27],
        [99, 29,  0, 99]]])