In [2]:
import numpy as np

In [3]:
#NumPy Indexing - 9/29/2021
x = np.array([[ -5,   2,  0, -7],
              [ -1,   9,  3,  8],
              [ -3,  -3,  4,  6]])

In [4]:
# Accessing the element located
# at row-1, last-column of `x`
x[1, -1]

8

In [5]:
# Access the subarray of `x`
# contained within the first two rows
# and the first three columns
x[:2, :3]

array([[-5,  2,  0],
       [-1,  9,  3]])

In [7]:
# NumPy fills in "trailing" slices
# if we don't supply as many indices
# as there are dimensions in that array
x[0]  # equivalent to x[0, :]


array([-5,  2,  0, -7])

In [10]:
y = np.array([[[ 0,  1,  2,  3],
              [ 4,  5,  6,  7]],

             [[ 8,  9, 10, 11],
              [12, 13, 14, 15]],

             [[16, 17, 18, 19],
              [20, 21, 22, 23]]])

In [11]:
# equivalent: `y[:, :, 0]`
y[..., 0]

array([[ 0,  4],
       [ 8, 12],
       [16, 20]])

In [12]:
# using an explicit tuple
y[(Ellipsis, 0)]

array([[ 0,  4],
       [ 8, 12],
       [16, 20]])

In [13]:
# equivalent: `y[0, :, 1]`
y[0, ..., 1]

array([1, 5])

An index *cannot* possess more than one Ellipsis entry.

In [19]:
z = np.array([[ 3.31,  4.71,  0.4 ],
              [ 0.21,  2.85,  3.21],
              [-3.77,  4.53, -1.15]])
x = np.array([[ 3.31,  4.71,  0.4 ],
              [ 0.21,  2.85,  3.21],
              [-3.77,  4.53, -1.15]])
z

array([[ 3.31,  4.71,  0.4 ],
       [ 0.21,  2.85,  3.21],
       [-3.77,  4.53, -1.15]])

In [20]:
subarray = z[:, 0] #If z changes, subbarray changes as well
subarray

array([ 3.31,  0.21, -3.77])

In [21]:
np.shares_memory(subarray, z) #np.shares_memory() checks if 2 NP arrays share a memeory (i.e. one refers to another)

True

In [22]:
np.shares_memory(x, z)

False

In [24]:
newsubarray = np.copy(subarray)

In [25]:
np.shares_memory(newsubarray, subarray)

False

In [27]:
#Math operations dont link arrays in memory
np.shares_memory(subarray+2, subarray)

False

In [28]:
#In-place Assignments
a = np.array([0, 1, 2, 3, 4]) 
b = a[:]
np.shares_memory(a, b)

True

In [30]:
# `a` is now assigned to reference a distinct array
a = np.array([0, -1, -2, -3, -4])
b

array([0, 1, 2, 3, 4])

In [33]:
np.shares_memory(a, b) #link is broken when `a` is changed

False

In [34]:
# reinitialize `a` and `b`.
# `b` is again a view of `a`
a = np.array([0, 1, 2, 3, 4])
b = a[:]
# assigning an array to a *view* of `a`
# causes NumPy to update the data in-place
a[:] = np.array([0, -1, -2, -3, -4])
a

array([ 0, -1, -2, -3, -4])

In [35]:
# `b` a view of the same data, thus it is affected by this in-place assignment
b

array([ 0, -1, -2, -3, -4])

In [36]:
np.shares_memory(a, b)

True

x += 5 instead of
x = x + 5


In [41]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
b = a[0]
c = a[0]

In [42]:
np.shares_memory(a, b) and np.shares_memory(a, c)


True

In [48]:
b = b * -1
np.shares_memory(a, b)

False

In [47]:
c *= -2
np.shares_memory(a, c)

True

In [53]:
a = np.array([0., 0.2, 0.4, 0.6, 0.8, 1.])
b = a[:]
np.shares_memory(a, b)


True

In [54]:
a = np.exp(a, out=a) #out= forces the output to go to a instead of making a new array
print(a)
print(b)

[1.         1.22140276 1.4918247  1.8221188  2.22554093 2.71828183]
[1.         1.22140276 1.4918247  1.8221188  2.22554093 2.71828183]


In [55]:
def add_3(x):
    x += 3
    return x

In [56]:
y = np.array([0, 1, 2])
z = add_3(y)
z

array([3, 4, 5])

In [57]:
y

array([3, 4, 5])

In [3]:
#Advanced Indexing 9-30
x = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])

rows = np.array([[0, 0],
                 [2, 2]])

cols = np.array([[0, 0],
                 [2, 2]])

x[rows, cols]

array([[0, 0],
       [8, 8]])

In [4]:
bool_index = np.array([[True, False, False],
                       [False, True, False],
                       [False, False, True]])

x[bool_index]

array([0, 4, 8])

In [6]:
np.shares_memory(x, x[rows, cols])


np.shares_memory(x, x[bool_index])


False

In [7]:
y = np.array([ 0, -1, -2, -3, -4, -5])
index = np.array([2, 4, 0, 4, 4, 4])
y[index]

array([-2, -4,  0, -4, -4, -4])

In [8]:
np.shares_memory(y, y[index])

False

In [11]:
z = np.array([[[ 0,  1,  2,  3],
               [ 4,  5,  6,  7],
               [ 8,  9, 10, 11]],

              [[12, 13, 14, 15],
               [16, 17, 18, 19],
               [20, 21, 22, 23]]])

# specifies subsequent sheets to access
ind0 = np.array([0, 1, 0])

# specifies subsequent rows to access
ind1 = np.array([0, 2, 1])

# specifies subsequent columns to access
ind2 = np.array([3, 3, 0])

z[ind0, ind1, ind2]

array([ 3, 23,  4])

In [12]:
ind0 = np.array([1, 1, 0, 1]).reshape(2, 2)
ind1 = np.array([1, 2, 0, 0]).reshape(2, 2)
ind2 = np.array([1, 3, 1, 3]).reshape(2, 2)
z[ind0, ind1, ind2]

array([[17, 23],
       [ 1, 15]])

In [14]:
x = np.array([[[-0.26,  0.49,  0.18],
               [ 0.43,  0.3 ,  0.29]],

              [[-0.44,  0.3 ,  0.28],
               [ 0.27, -0.09, -0.13]]])

bool_ind = x > 0

x[bool_ind]


array([0.49, 0.18, 0.43, 0.3 , 0.29, 0.3 , 0.28, 0.27])

In [15]:
bool_ind
np.where(bool_ind)

(array([0, 0, 0, 0, 0, 1, 1, 1], dtype=int64),
 array([0, 0, 1, 1, 1, 0, 0, 1], dtype=int64),
 array([1, 2, 0, 1, 2, 1, 2, 0], dtype=int64))